### ISSUE TITLE
ros_mary_tts: Cannot locate rosdep definition for [stdmsgs]

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_hri#1]
`rosdep install` produces the following error: `ros_mary_tts: Cannot locate rosdep definition for [stdmsgs]`.
I think there is just an underscore missing in the package.xml but I wanted to ask before I change anything. @marc-hanheide you did mean std_msgs, right?

**Comment by marc-hanheide** [comment]
Yes indeed I did... Sorry. Feel free to fix. Marc
