### ISSUE TITLE
[bellbot_gui] Keyboard allows access system

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_hri#109]
E.g., Alt+Tab allows to switch out of the browser. The functionality should be restricted to only have letters, numbers and shift.

EDIT: Forgot a "to" in the title...

**Comment by marc-hanheide** [comment]
That's why I want a js one :tongue:

**Comment by gatsoulis** [comment]
I have tried numerous solutions including js ones, but unfortunately none of them is working as intended except from the current to most extend... Had a look on the settings of the kbd and there is no option to remove alts/tabs.

**Comment by cdondrup** [comment]
@marc-hanheide didn't you want to try and include the js keyboard?

**Comment by marc-hanheide** [comment]
Oh, yes... among other things...

**Comment by cdondrup** [comment]
Not using the keyboard any more.
