### ISSUE TITLE
[ros_mary_tts] stops talking after some time

### ISSUE THREAD

**Issue by gestom** [strands-project/strands_hri#11]
After a few hours of continuous operation, ros_mary_tts does not talk anymore.

**Comment by marc-hanheide** [comment]
curious... could you send the logs?

**Comment by marc-hanheide** [comment]
Is this still happening?

**Comment by marc-hanheide** [comment]
I hope this is resolved by disabling logging in https://github.com/strands-project/strands_ui/pull/41 Please reopen if not
