### ISSUE TITLE
Hard Coded frame_id in QTC library

### ISSUE THREAD

**Issue by tejaspp** [strands-project/strands_hri#156]
I need to change the value of frame_id in the QTC library from "map" to another name. But since it is hard-coded, it cannot be changed.

Please allow it to be parametrized, so that it can be changed.

Thanks

**Comment by cdondrup** [comment]
That is a fair point. If you could create a pull request fixing that, that would be much appreciated.

**Comment by marc-hanheide** [comment]
fair point @cdondrup 

please @tejaspp do this.
