### ISSUE TITLE
Making repository private

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_hri#17]
As we (@cdondrup mainly) want to start developing our own not yet published research in the repository I'd like to make it private if that's not a problem. However, there is a general problem to that. If everybody starts making their own research repositories private (like strands_qsr) for example, we'll quickly run out of private repositories. So, what's the best strategy. We decided that @cdondrup 's work falls under HRI and there we'd put it here. But then we'd probably end up in the long run to make all repositories private :-1:  So, what's the policy? Shall I make this private? Or do something else?

**Comment by arbeitor** [comment]
I think the best way to handle this and how we are going to do it (specially for unfinished parts being exclusively developed by us) is to use external repositories that get pulled out on the robot or other places. I could imagine, 
it might be useful to have a single private repository (on strands github) that has the information or procedures to check the repos out (with strands username and password). In this way, it will be possible to test them regularly on jenkins.

**Comment by hawesie** [comment]
This is an interesting management problem. I think the strands-project private repos should be prioritised for cross-consortium integration work that is not yet ready to be made public (e.g. strands_qsr is being used for an initial WP4 collaboration). We currently have 5 private repos left, so I'm happy for @cdondrup to take one now, and we can reassess when we're closer to the limit.

**Comment by marc-hanheide** [comment]
So, @hawesie suggests to create a separate one... @cdondrup, I was also thinking you could develop you code within the https://github.com/strands-project/strands_perception_people repo. That on is private and you are already collaborating with Dennis@RWTH anyway.

**Comment by cdondrup** [comment]
Yes, I could also use the perception people one but I am not sure if that fits the desired outcome because it is not really about perception but interaction so it might not be very intuitive to put it there. But I wouldn't mind to use the repo for now and move it to another one once it's published.
