### ISSUE TITLE
[ros_mary_tts] Werner's voice

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_hri#20]
This is a question for the Vienna guys (I think mainly @ToMadoRe):
Which voice are you using for Werner? We want to try out the memory_game and since the robot is supposed to speak German and should sound male, I thought you might already have a voice you use. If so, can you commit the configuration you are using (maybe as a new branch)? If not we will choose one for you ;)

**Comment by ToMadoRe** [comment]
No, we don't have a particular voice for Werner. So far, we have just used "dfki-spike-hsmm" as far as I can remember. So,I guess we are happy with any (male) voice you can provide :)

**Comment by cdondrup** [comment]
You can play with the two german voices I installed if you like. See which one you like better. See README for how to set voices. If you don't care, I will decide ;)

**Comment by TobKoer** [comment]
would it be to change the voice?
As far as we are concerned 'Werner' is only an internal name for the consortium. We won't introduce the robot as Werner at the care site and rather try to motivate people there to vote for their own name. So maybe, in the end people might choose a female name...;-)

**Comment by cdondrup** [comment]
Changing the voice is not difficult and just one line in a config file. We could use the voice they use on their Robot in Bielefeld where the memory game was developed. This is supposed to be quite neutral but sounds rather female to me to be honest. Maybe @AndreasKipp can say something about that.

**Comment by AndreasKipp** [comment]
We currently use the female german voice and pitch it (f0add=90) to sound more like a child. For the memory game it should be no problem if the voice is male.

At some points in a game (example: robot has no pair) the voice will be slowed down to sound a little bit sad. This should work with the male voice too.

**Comment by cdondrup** [comment]
No, for the memory game it works perfectly but if they don't want to influence people's perception of the robots gender what would you recommend? Your voice? @AndreasKipp

**Comment by AndreasKipp** [comment]
The outer buddy of the robot is not male or female at all. So for that no need to be female. For our robot we have seen that in our study the female version was very well accepted. We only had male participants. Maybe there is sterotyped thinking and for that playing with a female robot maybe more accepted? Do you have some role setting for your robot for all other interactions?

**Comment by TobKoer** [comment]
I think, whether playing the game or not, the robot should always have the same voice. Otherwise this is confusing for users and does not make for a 'coherent' personality of it.

**Comment by AndreasKipp** [comment]
Yes no question about that. For me it is not important if its male or female.
