### ISSUE TITLE
make voice and intonation configurable via actionlib parameters

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_hri#3]

**Comment by marc-hanheide** [comment]
Not sure... did @cdondrup not do anything in this direction?

**Comment by cdondrup** [comment]
It's two services, one for the locale and one for the voice atm. Could probably make it dynamically reconfigurable parameters instead... But that won't happen before the marathon. Description of how to use it is in the mary README.

**Comment by marc-hanheide** [comment]
good enough for me ATM... we shall close this for now
