### ISSUE TITLE
Simple touchscreen interface for robot control

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_hri#4]
It would be useful to have a simple touchscreen interface running on the robot to allow you to interact with it. Possible functionality may be
- Pause/resume execution (e.g. during patrolling)
- Send to docking station
- Simple teleop 

It would be good if the UI was extensible so we can extend it with functionality easily in the future.

**Comment by marc-hanheide** [comment]
As part of the UOL "summer of code" project, "my" students have created a [simple GUI](https://github.com/LCAS/uol-openday-robot/tree/master/rqt_openday_gui) for our open day robot demo. From this experience I can recommend implementing such a GUI as an [rqt](http://ros.org/wiki/rqt) plugin. Was pretty straight forward.

**Comment by hawesie** [comment]
I'm planning to have a bit of a play with this in the next week or so. I've had two suggestions of approaches to take: rqt and web. The advantage of rqt is that it has all the built-in ros stuff. The advantage of web is that it is very portable and could be run on additional devices (tablets etc.) and reused in other contexts. I'm also conscious of the requirement to run the GUI in a "kiosk mode" so that people can only access the functionality of the robot's PC that we want to expose. This can probably be done via a stand-alone x server somehow.
