### ISSUE TITLE
human_aware_navigation.py uses hardcoded fast parameters

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_hri#86]
These should be configurable in some way.

**Comment by cdondrup** [comment]
We changed that during rhe first deployment. Usually they took the one that they found move-base to use before. I can make them configurable, though.

**Comment by hawesie** [comment]
Taking the value from move_base would be good. We only found this because we configured bob to run more slowly, but then turned on h_a_n and were puzzled as to why he was actually going faster!=

**Comment by cdondrup** [comment]
Sorry for that. I will reimplement that in a more clever way.

**Comment by Jailander** [comment]
Hi, this is still causing problems now that execute policy server is reconfiguring the speed constantly since https://github.com/strands-project/strands_navigation/pull/234

**Comment by cdondrup** [comment]
I knew that would bit me in the back at some point ;)
I'll fix it asap.
