### ISSUE TITLE
[bellbot] broken install targets

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_hri#92]
When trying to run catkin_make install:

```
error: package directory 'src/bellbot_scheduler' does not exist
CMake Error at strands_hri/bellbot_scheduler/catkin_generated/safe_execute_install.cmake:4 (message):

  execute_process(/home/cdondrup/ros_ws/build/strands_hri/bellbot_scheduler/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  strands_hri/bellbot_scheduler/cmake_install.cmake:36 (INCLUDE)
  cmake_install.cmake:135 (INCLUDE)

```

**Comment by marc-hanheide** [comment]
you want to assign somebody of the team, or it will not be seen

**Comment by cdondrup** [comment]
I'll assign @yianni for now, trusting that he knows who implemented this ;)

**Comment by marc-hanheide** [comment]
clearly the whole `src/` dir is missing

**Comment by gatsoulis** [comment]
I think this was to manually schedule bellbot tasks for the demonstration purposes. @RaresAmbrus Correct?

**Comment by marc-hanheide** [comment]
We should ask @Jailander. I think he imported this here...

**Comment by Jailander** [comment]
yes, but I am not sure what is missing, I checked when I moved everything and the structure seemed correct and the compilation worked ok, @yianni can you check please, I currently have my hands full with other things

**Comment by cdondrup** [comment]
Fix hint: Remove `setup.py`, comment [this line](https://github.com/strands-project/strands_hri/blob/hydro-devel/bellbot_scheduler/CMakeLists.txt#L11) and create a proper install target for the script in `scrips`.

**Comment by gatsoulis** [comment]
@Jailander Sure I can have a look but from Monday as I am currently out of my office.
@cdondrup Thanks for hint.

**Comment by Jailander** [comment]
Ok, maybe @kunzel, @RaresAmbrus or @Pandoro can help here if they are online

**Comment by marc-hanheide** [comment]
it was two lines... done it... #93

**Comment by marc-hanheide** [comment]
I suppose

**Comment by Jailander** [comment]
Thank you Marc
